version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  moospire-server:
    build:
      context: .
  redis:
    image: redis:alpine